Update hpa.yaml
proagrica/helm-charts pull request #53
Opened 2023-07-18 14:59 UTC by wiseman13

Use v2 api for HorizontalPodAutoscaler

2023-07-18 15:34 UTC, SecaraR requested changes
Hi Scott,

It seems version 0.8.0 would need to be mentioned inside the CHANGELOG file as well.

https://github.com/proagrica/helm-charts/blob/18c6cf6c35dbc4199778387be54f2b9f87415184/charts/clamav/CHANGELOG.md?plain=1#L13

2023-07-19 14:29 UTC, wiseman13 commented
Yep looks like when you did the 0.8 version you had not updated the change log or the readme. I have now added those entries and those for the 0.9 to the commit now.

2023-07-20 08:17 UTC, SecaraR commented
> Yep looks like when you did the 0.8 version you had not updated the change log or the readme. I have now added those entries and those for the 0.9 to the commit now.

That's right Scott, I missed making those updates at the time when I updated the ClamAV version. 
I think all looks good.

On a separate note, 
I now realise I should have done the same for the influxdb helm chart as well. I'll open a separate pull request for that.

2023-07-20 08:19 UTC, SecaraR approved these changes

2023-07-20 15:48 UTC, merged